# Generated by Django 4.2.16 on 2024-12-05 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researchdata', '0002_data_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='geo_bounding_box',
            field=models.TextField(blank=True, help_text='If available, provide bounding box data for this location. Otherwise specify lat/long below.', null=True),
        ),
    ]
